version: "3.3"
services:
  postgresbd:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "kanalservicedb"
      POSTGRES_USER: "alex"
      POSTGRES_PASSWORD: "kanalservice"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  data_collector:
    build: ./data_collector
    depends_on:
      - postgresbd
    links:
      - postgresbd
    ports:
      - "8080:80"
